title: Sudoo's Blog
description: >-
  Welcome to my personal blog.
baseurl: ""
url: "https://www.sudoo.me"

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true

markdown: kramdown
